[package]
name = "cirg-cli"
version = "3.0.0"
edition = "2024"

[dependencies]
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }
cirg = { path = "../cirg" }
serde_json = "1.0.149"
system-pause = "0.1.2"