[package]
name = "cirg-cli"
version = "3.0.0"
edition = "2024"

[dependencies]
anyhow = "1.0.101"
cirg = { path = "../cirg" }
serde = "1.0.228"
serde_json = "1.0.149"
system-pause = "0.1.2"
tokio = { version = "1.49.0", features = ["macros", "rt-multi-thread"] }